### PR TITLE
Updated serializer for AMS

### LINKED ISSUE #42: Update serializer.js to use AMS addon for ember-data
Ember Data 2.0 deprecated AMS being part of active record and is now part of a plugin. https://github.com/wildland/trailhead/blob/master/boilerplates/serializer.js#L3 needs updated to use this plugin, and the application template needs updated to install this plugin. See https://github.com/ember-data/active-model-adapter

### PR DESCRIPTION
**Pull request by chadzink**
Fixes #42 

Also changed Rails to version 4.2.10 (minor update).

### CODE REVIEW

**Review by jweakley — APPROVED** [review]
👍 visual code review.

**Comment by jweakley** [comment]
@chadzink, we should get @Samsinite's input on this.

**Review by Samsinite — APPROVED** [review]
Helped him fix the issue he ran into :)

**Review by Samsinite — CHANGES_REQUESTED** [review]
Actually, we need to make sure `active-model-adapter` gets installed as well :)

**Comment by chadzink** [comment]
@Samsinite Added the `active-model-adapter` to the build process.

**Review by Samsinite — APPROVED** [review]

**Pull request merged**
